# Generated by Django 4.0.5 on 2022-07-03 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.FloatField(blank=True, null=True)),
                ('nota2', models.FloatField(blank=True, null=True)),
                ('nota3', models.FloatField(blank=True, null=True)),
                ('promedio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'curso_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('birthday', models.CharField(blank=True, max_length=55, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=55, null=True)),
                ('last_name', models.CharField(blank=True, max_length=55, null=True)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='proyecto.users')),
            ],
            options={
                'db_table': 'user_roles',
                'managed': False,
            },
        ),
    ]
